USD Integration
google-deepmind/mujoco pull request #1413
Opened 2024-02-12 14:37 UTC by awesome-aj0123

Three files:
- mujoco/python/mujoco/usd_exporter.py
- mujoco/python/mujoco/usd_component.py
- mujoco/python/mujoco/usd_utils.py

The USD exporter class handles all the overall USD file and materials. The USD component files handles all the objects in the scene.

2024-02-15 15:31 UTC, nimrod-gileadi requested changes
First look.

2024-02-15 15:31 UTC, nimrod-gileadi commented on python/dist/mujoco-3.0.2.tar.gz
Remove from this PR.

2024-02-22 02:35 UTC, yuvaltassa commented
Let's delete the `usd_` prefix to avoid stuttering. `usd/component.py` etc.

2024-02-22 15:15 UTC, nimrod-gileadi approved these changes

2024-02-22 15:15 UTC, nimrod-gileadi commented on python/mujoco/__init__.py
> +from mujoco.usd.usd_exporter import USDExporter
Remove these imports so the module can be loaded separately.

2024-03-01 19:00 UTC, crewmatt approved these changes

2024-03-01 19:07 UTC, crewmatt approved these changes

2024-03-06 11:41 UTC, yuvaltassa commented
This needs to be rebased.
Probably better to just close this PR and start a new one at head? 
The discussion is long and mostly irrelevant...

2024-05-03 01:48 UTC, closed without merging