Tutorial for how to use the jacobian of mjx.step
google-deepmind/mujoco pull request #1601
Opened 2024-04-17 10:22 UTC by Andrew-Luo1

A notebook showing how to use vanilla policy gradients to accelerate policy learning, thanks to MJX's differentiability. Demonstrations are given for imitation learning and locomotion, for a quadruped. Requires [Brax PR 476](https://github.com/google/brax/pull/476).

**Supporting changes**
1. Add an Anymal C model, cleaned for faster simulation on MJX similarly to MJX [Barkour](https://github.com/google-deepmind/mujoco/tree/main/mjx/mujoco/mjx/test_data/barkour_v0)
2. Add an image for the notebook

2024-04-18 22:09 UTC, erikfrey commented
Exciting!  How many changes did you make to anymal?  Can you try this:

- Make a PR to mujoco menagerie with `anymal_c_mjx.xml` and `scene_mjx.xml` with your anymal modifications
- Somewhere at the top of your colab, do:

```sh
!git clone https://github.com/google-deepmind/mujoco_menagerie.git
```

Then you should be able to remove the anymal assets from this PR.  Let me know if that works!

2024-04-19 04:55 UTC, Andrew-Luo1 commented
Hi Erik, I've proposed [Menagerie PR 50](https://github.com/google-deepmind/mujoco_menagerie/pull/50) with the Anymal C updates, and have documented the modifications in the readme. I've updated this notebook as well.

The formatting of this notebook isn't quite the same as the current mujoco notebooks. In the case that this PR goes through, of course feel free to modify it as you see fit: adding the Mujoco banner, adding a colab instance, etc!

And let me know if there's anything I can do to bring the notebook more up to standards.

2024-04-22 23:20 UTC, erikfrey requested changes
OK, I see your change is incorporated into menagerie.  Looking great!  One last nit and we will merge.

2024-04-22 23:20 UTC, erikfrey commented on mjx/pyproject.toml
> +Changelog = "https://mujoco.readthedocs.io/en/3.1.5/changelog.html"
I suspect this is an unneeded change - can you revert?  Otherwise, let me know what this is for.

2024-04-24 17:51 UTC, merged