elastoplastic extension
google-deepmind/mujoco pull request #560
Opened 2022-11-03 22:14 UTC by mathl79

implementation of the plasticity extension idea to the elasicity plugin. 
see: [https://github.com/deepmind/mujoco/discussions/549](url)

- new xml config parameter yield stress ("yield"  [Pa]). Yield separates the elastic from the plastic domain
- generation of userdata output: von mieses equivalent stress, curvature, strain(change of curvature)
- skin/composit stress coloring
- skin per vertex color added to the datamodel
- CMAKE config of elasticity.dll changed to destination output folder \plugin\ 
- new test model xml file

googletest is not implemented yet --> need help to find sufficient test criterias

2022-11-03 22:25 UTC, mathl79 commented
Hi! 
I never started a pull request before. 
So in order to fulfill the contribution requirements and adopt best practices, i am hoping for some beginner friendly remarks and some guidance.

2022-11-04 17:54 UTC, quagla commented
Hi @mathl79 I think you have changed something in the default behavior of the cable? It looks like the test for the exact solution of the cantilever beam fails.

Great that you are visualizing the stresses, this is something I always wanted to do!

2022-11-06 05:44 UTC, mathl79 commented
thank you for taking a look.
The string loaded elasticity test model does not have the required  "yield" Parameter as it is a elastic  test only.
I need to set a infinite yield value in case the "yield" Parameter in the XML is missing at the cable constructor.
In that way, the test model should be loaded and run as expected.

2022-11-07 11:57 UTC, quagla commented
Do you mean that you updated `CantileverIntoCircle` in `elasticity_test`? I don't see that file in your commit.

2022-11-08 06:57 UTC, mathl79 commented
The default elastic behavior should no be changed, if the new parameter "yield" is infinite. I missed to implement the default setting and remove the parameter check in this pull request, so the elasticity_test fails.

In the meantime i reworked my version to have a material model with strain hardening. 
![image](https://user-images.githubusercontent.com/88651276/200494693-55c1d59b-2255-49ce-9da0-cd0f0dd75996.png)

Should i close this Pull draft and start a new branch in my fork with the advanced model ?

2022-11-08 08:13 UTC, quagla commented
Great! I think it's fine if you keep pushing new commits to this branch, the PR should be updated automatically.

2022-11-08 16:58 UTC, quagla commented
Thanks for the revised version! My main comments are:

- Why did you add so much damping to the original cable examples?
- Did you try the original examples and particularly to run `elasticity_test`? The default (purely elastic) behaviour has changed and it seems incorrect.
- More generally, can we break the PR into a visualization and a plasticity PR or would that be impossible?

2022-11-08 19:21 UTC, mathl79 commented
I tried to implement a plasticity deformation proportional damping by reducing the torque depending on the change of omega an the Volume. 
 Now i see, that this additional damping is overlapping with the elastic joint damping. This needs to be separated.

I did not run the tests - but better should have...

So I will change back to the standard plugin models, add extra plastic test models and separate the viscous damping by only applying it, if elements are in plastic domain.

I try to separate the coloring feature from the plasticity as you suggested.
For the coloring, i assume it should be configurable by XML options, right ?
-definition of range (min,  max,  auto)
-constant RGB color below lower limit 
-constant RGB color above upper limit 
-color palette
-enable/disable

What else needs to be user controllable ?

Should any scalar properties other than equivalent stress be selectable in future ? 

Besides the separation from the plasticity, zhe stress needs to be calculated for the elasticity model anyway, in order to be able to show it.

Btw - what is a good place in the source for the color conversion and palette generation tools, that I have put inside the plugin code from now?

Is this something, that could be used generally or should it stay plugin specific?

2022-11-09 06:02 UTC, mathl79 commented
I tried to implement a plasticity deformation proportional damping by reducing the torque depending on the change of omega an the Volume. 
 Now i see, that this additional damping is overlapping with the elastic joint damping. This needs to be separated.

I did not run the tests - but better should have...

So I will change back to the standard plugin models, add extra plastic test models and separate the viscous damping by only applying it, if elements are in plastic domain.

I try to separate the coloring feature from the plasticity as you suggested.
For the coloring, i assume it should be configurable by XML options, right ?
-definition of range (min,  max,  auto)
-constant RGB color below lower limit 
-constant RGB color above upper limit 
-color palette
-enable/disable

What else needs to be user controllable ?

Should any scalar properties other than equivalent stress be selectable in future ? 

Besides the separation from the plasticity, zhe stress needs to be calculated for the elasticity model anyway, in order to be able to show it.

Btw - what is a good place in the source for the color conversion and palette generation tools, that I have put inside the plugin code from now?

Is this something, that could be used generally or should it stay plugin specific?

2022-11-09 09:41 UTC, mathl79 commented
Hi,  
i did run the tests on my windows machine and all configured tests do pass. 
But the `PluginTest.CantileverIntoCircle` is not even executed. Also the github build check showes, that the windows-2022 build does not run the elasticity tests, but fails at installing the file elasticity.dll into the plugin folder.

I don't know how to correct the config tests.

When building /debugging elasticity.dll, the file is placed into the /bin folder and needs to be copied into the /bin/plugin/ subfolder manually to be recognized as plugin. 

I think, that is also linked to the problem above.

2022-11-09 09:53 UTC, quagla commented
OK that's interesting, there is something broken with Windows then because on the main branch the dll gets copied. @saran-t what are your thoughts?

As mentioned in my previous comment, could you please open a new PR for the visualisation part? You can keep this one open as well and we will get back to it once we complete the visualisation. How does that sound to you? Maybe in the meantime we can fix the Windows issues as well.

2022-11-09 09:54 UTC, mathl79 commented
https://github.com/deepmind/mujoco/blob/7b7fc09d1fc3d9a970b2123bc41c4d1fbcff35d6/test/CMakeLists.txt#L69-L71

This code excludes the plugin-test from the test config for Windows builds. what is the reason for this?

2022-11-09 10:07 UTC, quagla commented
Good point, we definitely need to fix Windows. Now I remember we disabled the test because we had some issues loading the DLL. I wonder if your change to CMakeList fixes that? Perhaps you want to open a third PR with only that change and also enabling again the plugin tests for Windows by deleting the lines you quoted in your post?

2022-11-11 09:53 UTC, quagla commented
My suggestion is that we can start from the visualization PR since that doesn't requires the windows tests.

2022-11-17 13:08 UTC, quagla commented
Hi @mathl79 I'm pleased to let you know that now you can run plugin tests on Windows as well, see https://github.com/deepmind/mujoco/commit/a9781d9beafd5b078538d41548065bebda6f99aa

2022-11-17 13:22 UTC, mathl79 commented
Perfect, thanks!
 I was also at the point to implement the runtime dll loading, as I was not able to link the plugin into the elasticity-test executable at compile time.

2022-11-17 13:24 UTC, mathl79 commented
btw. - you can test the branch for the stress skin visuals without the plasticity in my fork.

2022-11-17 14:56 UTC, quagla commented
Looks like we have to rollback the commit unfortunately, hopefully we'll be able to fix it and activate the windows tests in the next days.

2022-11-17 17:28 UTC, quagla commented
Good news, Windows is fixed if you rebase from https://github.com/deepmind/mujoco/commit/043ed273a7e90d4f70cc8fcfad8d5f21ffe81eca you'll be able to run Windows tests. 

For the visualisation, are you going to create a separate PR from your branch or would you prefer if we have a look and apply the changes ourselves?

2022-11-17 18:42 UTC, mathl79 commented
Perfect ! Thanks for fixing again!

For me it absolutely ok, if you take my approach as basis to implement the coloring by our own. 
I do have the feeling, that my implementation is not generic enough to fit into a public release.

2022-11-28 11:04 UTC, quagla commented
Hi @mathl79 we are having a look the colouring internally (see https://github.com/deepmind/mujoco/pull/599).

I wanted to ask you what is the rationale for the Von Mises stress computed directly from the curvature stresses without membrane ones? Does this plastic model fit your needs?

2022-11-29 06:24 UTC, mathl79 commented
Hi @quagla, 
for me the intention for the coloring was just to have an visual indicator for the effects of plasticity. 
The average bending stress is for my case enough information and the projected surface stress calculation of the skin elements was/is to difficult for me. 
Also the coloring on bone level allows non-skin compounds to be colorized.

Regarding the plasticity model:
In the meantime i changed my plasticity model in the way, that omega0 remains unchanged, but the internal bending stress / remaining strain is stored. In that way, the hysteresis behavior is working correctly now, which i did not achive with my first attempt.

I hope, that i will have some spare time the next days to finalize my testing and commit that change into my branch.

br,

Mathias

2022-11-29 10:32 UTC, quagla commented
Great to hear! Do you think you can write a unit test in `elasticity_test` comparing the reference vs computed hysteresis so any future change will make sure to not break your intended behaviour?

For the skin colouring, after an internal discussion it was decided to do it in a different way so we will have to implement it ourselves. I agree however that colouring geometries (bones) is probably already giving plenty of information so when you are committing your final changes you could perhaps leave the geom colouring but remove the skin part if you can?

By the way, I added a Jet color palette in my branch, maybe you like it https://github.com/deepmind/mujoco/pull/599/files#diff-f8ed3e4597989d57bd3588f824c10fe89b140ca2665a05dd3b8878f2f6f6c23b

2022-11-30 10:27 UTC, quagla commented
Thanks for the update!

Tip: I think you have to set the parameters of CantileverIntoCircle such that perfect elasticity is obtained without triggering a warning because warnings cause test failures.

[ RUN      ] PluginTest.CantileverIntoCircle
D:\a\mujoco\mujoco\test\fixture.cc(43): error: Failed
mju_user_warning: YieldStress is notset: perfect elasticity is assumed !

2022-12-01 14:09 UTC, quagla requested changes
I left some comments. First of all, great work! However some things must be address before continuing:

- The original tests and the original examples must be working.
- A new test for plasticity should be added.
- It would be great to remove the visualization part from the branch, unless absolutely necessary (we should use the test to validate the results instead).

2022-12-01 14:09 UTC, quagla commented on plugin/elasticity/cable.cc
> +      k_deltaStrain_E = 5 / (UtStrain - YieldStrain_E); //exponential constant for bending strain hardening
Are these 3 variables unused?

2022-12-01 14:09 UTC, quagla commented on plugin/elasticity/cable.cc
> +void scalar2rgba(float rgba[4], mjtNum Scalar, mjtNum min, mjtNum max) {
As mentioned in the main discussion, it would be great to remove the coloring part from this branch.

2022-12-01 14:09 UTC, quagla commented on plugin/elasticity/cable.cc
> +void LocalForce(mjtNum qfrc[3], mujoco::plugin::elasticity::Cable::stiffness_ Sel, mujoco::plugin::elasticity::Cable::stiffness_consts_ Sconst,
Is the full namespace needed?

2022-12-01 14:09 UTC, quagla commented on plugin/elasticity/cable.cc
> +    //actual strain
could you always add a space between // and the comment?

2022-12-01 14:09 UTC, quagla commented on plugin/elasticity/cable.cc
> +    mjtNum Yield_stress_top[] = {
Could you document this plastic model with e.g. a paper or a link and/or a more detailed explanation in the code?

2022-12-01 14:09 UTC, quagla commented on plugin/elasticity/cable.cc
> +      mju_warning("YieldStress is notset: perfect elasticity is assumed !");
Please update elasticity_test such that this warning is not triggered.

2022-12-01 14:09 UTC, quagla commented on model/plugin/belt.xml
> +      <joint kind="main" damping="10"/>
If I load this model, it immediately explodes.

2022-12-01 14:09 UTC, quagla commented on model/plugin/coil.xml
> +        <config key="twist" value="1e10"/>
When I pull the second spring, at some point it looks like the simulation blows up.

2022-12-02 19:36 UTC, quagla commented
We have added coloring of the geometries using a callback, please see https://github.com/deepmind/mujoco/commit/0d52feaa948b92f4ff0e2f844cb51c1d38df1b79

2023-03-01 11:42 UTC, quagla commented
Hi @mathl79 are you still interested in submitting this?

2026-09-08 07:27 UTC, yuvaltassa commented
closing due to inactivity

2026-09-08 07:27 UTC, closed without merging